### ISSUE TITLE
Feat: Check semgrep report and apply necessary changes

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#427]
Feat: Fix semgrep output

You can find the semgrep output in the artificats (CI -> Security -> semgrep-cairo

**Comment by ametel01** [comment]
sempgrep report only points out the use of unsafe math operators across the repo eg. 
```
Call unsafe math operators on len                   
                                                              
          423┆ let exit = len + offset;
```
Which approach do we want to take on this?

**Comment by ametel01** [comment]
In light of our specific requirements, I propose that we define our own set of Semgrep rules instead of relying on an external rule set like AVNU's. This will allow for a more tailored behavior of the tool to our codebase. For reference, AVNU's rule list can be found [here](https://github.com/avnu-labs/semgrep-cairo-rules/blob/main/RULES.md).

I'm willing to take on the task of implementing these custom rules once we've agreed on the standards. Thoughts?

**Comment by ametel01** [comment]
@Sk8erboi84 for now i will limit the changes to replace `unwrap()` with `expect()` for better error handling and add checks for division by zero.

**Comment by ametel01** [comment]
@Sk8erboi84 this can be closed.
